// Elenco progetti: aggiungi/rimuovi voci qui per aggiornare sia la griglia
// portfolio che le pagine di dettaglio. "category" alimenta automaticamente
// il menu filtri della mascotte. "images" è l'elenco di tutte le tavole del
// progetto, mostrate una sotto l'altra nella pagina di dettaglio. La
// copertina mostrata nella griglia è "cover" quando presente (in genere un
// file "_preview" pensato solo per il portfolio), altrimenti la prima
// immagine di "images" — "cover" non viene mai mostrata nella pagina di
// dettaglio del progetto.
//
// L'ordine qui sotto è stato pensato apposta per la resa visiva della
// griglia (alterna categorie e proporzioni verticali/orizzontali): se
// aggiungi un progetto nuovo, prova a inserirlo vicino a uno con
// orientamento opposto piuttosto che in fondo alla lista.
//
// NOTA: anno e categoria di alcuni progetti sono una mia stima (non avevo
// questi dati) — correggili pure in questo file, è l'unico posto da toccare.
const PROJECTS = [
  {
    slug: "il-tenace-soldatino-di-stagno",
    title: "Il tenace soldatino di stagno",
    type: "Picture book",
    year: "2025",
    category: "children",
    tags: ["Children", "Picture book"],
    images: [
      "images/projects/il-tenace-soldatino-di-stagno/copertina.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/1-2.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/3-4.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/5-6.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/7-8.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/9-10.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/11-12.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/13-14.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/15-16.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/17-18.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/19-20.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/21-22.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/23-24.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/25-26.jpg",
      "images/projects/il-tenace-soldatino-di-stagno/retro.jpg",
    ],
  },
  {
    slug: "il-buio-oltre-la-siepe",
    title: "Il buio oltre la siepe",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Book"],
    images: [
      "images/projects/il-buio-oltre-la-siepe/ed_il-buio-oltre-la-siepe_1.jpg",
      "images/projects/il-buio-oltre-la-siepe/ed_il-buio-oltre-la-siepe_2.jpg",
      "images/projects/il-buio-oltre-la-siepe/ed_il-buio-oltre-la-siepe_3.jpg",
      "images/projects/il-buio-oltre-la-siepe/ed_il-buio-oltre-la-siepe_4.jpg",
      "images/projects/il-buio-oltre-la-siepe/ed_il-buio-oltre-la-siepe_5.jpg",
    ],
  },
  {
    slug: "cura",
    title: "Cura",
    type: "Personal work",
    year: "2026",
    category: "personal",
    tags: ["Personal work", "Poster"],
    images: [
      "images/projects/cura/alessandro-rossi-cura.jpg",
    ],
  },
  {
    slug: "aromi-del-cambiamento",
    title: "Aromi del cambiamento",
    type: "Editorial",
    year: "2025",
    category: "editorial",
    tags: ["Editorial", "Food"],
    images: [
      "images/projects/aromi-del-cambiamento/ed_aromi.jpg",
      "images/projects/aromi-del-cambiamento/ed_aromi_1.jpg",
      "images/projects/aromi-del-cambiamento/ed_aromi_2.jpg",
      "images/projects/aromi-del-cambiamento/ed_aromi_3.jpg",
      "images/projects/aromi-del-cambiamento/ed_aromi_4.jpg",
      "images/projects/aromi-del-cambiamento/ed_aromi_5.jpg",
      "images/projects/aromi-del-cambiamento/ed_aromi_6.jpg",
    ],
  },
  {
    slug: "all-quiet-on-the-western-front",
    title: "All Quiet on the Western Front",
    type: "Cover",
    year: "2026",
    category: "cover",
    tags: ["Cover", "Book"],
    cover: "images/projects/all-quiet-on-the-western-front/all-quiet-preview.jpg",
    images: [
      "images/projects/all-quiet-on-the-western-front/all-quiet-1.jpg",
      "images/projects/all-quiet-on-the-western-front/all-quiet-2.jpg",
    ],
  },
  {
    slug: "il-gelo",
    title: "Il gelo",
    type: "Personal work",
    year: "2025",
    category: "personal",
    tags: ["Personal work"],
    images: [
      "images/projects/il-gelo/ed_il-gelo.jpg",
      "images/projects/il-gelo/ed_il-gelo_1.jpg",
      "images/projects/il-gelo/ed_il-gelo_2.jpg",
      "images/projects/il-gelo/ed_il-gelo_3.jpg",
      "images/projects/il-gelo/ed_il-gelo_4.jpg",
    ],
  },
  {
    slug: "design-week",
    title: "Design Week",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Event"],
    images: [
      "images/projects/design-week/ed_design.jpg",
    ],
  },
  {
    slug: "sole-amico",
    title: "Sole amico",
    type: "Children",
    year: "2026",
    category: "children",
    tags: ["Children", "Editorial"],
    images: [
      "images/projects/sole-amico/uppa-01.jpg",
      "images/projects/sole-amico/uppa-02.jpg",
      "images/projects/sole-amico/uppa-03.jpg",
      "images/projects/sole-amico/uppa-04.jpg",
      "images/projects/sole-amico/uppa-05.jpg",
      "images/projects/sole-amico/uppa-06.jpg",
    ],
  },
  {
    slug: "liber",
    title: "Liber 150",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Magazine"],
    images: [
      "images/projects/liber/alessandro-rossi-liber150-cover.jpg",
      "images/projects/liber/alessandro-rossi-liber150-nibali-01.jpg",
      "images/projects/liber/alessandro-rossi-liber150-silei-01.jpg",
      "images/projects/liber/alessandro-rossi-liber150-viaggiare-ci-fa-grandi-01.jpg",
    ],
  },
  {
    slug: "poste-dappertutto",
    title: "Poste dappertutto",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Advertising", "Il Sole 24 Ore"],
    images: [
      "images/projects/poste-dappertutto/ed_poste-dappertutto.jpg",
      "images/projects/poste-dappertutto/mock_poste-dappertutto.jpg",
    ],
  },
  {
    slug: "lultimo-uomo",
    title: "L'ultimo uomo sulla Terra",
    type: "Comic",
    year: "2026",
    category: "comics",
    tags: ["Comic", "Personal work"],
    images: [
      "images/projects/lultimo-uomo/alessandro-rossi-lultimo-uomo.jpg",
    ],
  },
  {
    slug: "inktober-2025",
    title: "Inktober 2025",
    type: "Personal work",
    year: "2025",
    category: "personal",
    tags: ["Personal work", "Inktober"],
    images: [
      "images/projects/inktober-2025/ed_inktober_1.jpg",
      "images/projects/inktober-2025/ed_inktober_2.jpg",
      "images/projects/inktober-2025/ed_inktober_3.jpg",
      "images/projects/inktober-2025/ed_inktober_4.jpg",
      "images/projects/inktober-2025/ed_inktober_5.jpg",
      "images/projects/inktober-2025/ed_inktober_6.jpg",
      "images/projects/inktober-2025/ed_inktober_7.jpg",
      "images/projects/inktober-2025/ed_inktober_8.jpg",
      "images/projects/inktober-2025/ed_inktober_9.jpg",
      "images/projects/inktober-2025/ed_inktober_10.jpg",
      "images/projects/inktober-2025/ed_inktober_11.jpg",
      "images/projects/inktober-2025/ed_inktober_12.jpg",
      "images/projects/inktober-2025/ed_inktober_13.jpg",
      "images/projects/inktober-2025/ed_inktober_14.jpg",
      "images/projects/inktober-2025/ed_inktober_15.jpg",
      "images/projects/inktober-2025/ed_inktober_16.jpg",
      "images/projects/inktober-2025/ed_inktober_17.jpg",
      "images/projects/inktober-2025/ed_inktober_18.jpg",
      "images/projects/inktober-2025/ed_inktober_19.jpg",
      "images/projects/inktober-2025/ed_inktober_20.jpg",
      "images/projects/inktober-2025/ed_inktober_21.jpg",
      "images/projects/inktober-2025/ed_inktober_22.jpg",
      "images/projects/inktober-2025/ed_inktober_23.jpg",
      "images/projects/inktober-2025/ed_inktober_24.jpg",
      "images/projects/inktober-2025/ed_inktober_25.jpg",
      "images/projects/inktober-2025/ed_inktober_26.jpg",
      "images/projects/inktober-2025/ed_inktober_27.jpg",
      "images/projects/inktober-2025/ed_inktober_28.jpg",
      "images/projects/inktober-2025/ed_inktober_29.jpg",
      "images/projects/inktober-2025/ed_inktober_30.jpg",
      "images/projects/inktober-2025/ed_inktober_31.jpg",
    ],
  },
  {
    slug: "i-know-you",
    title: "I Know You!",
    type: "Comic",
    year: "2026",
    category: "comics",
    tags: ["Comic", "Children"],
    cover: "images/projects/i-know-you/alessandro-rossi-anorak-crow-story-preview.jpg",
    images: [
      "images/projects/i-know-you/alessandro-rossi-anorak-crow-story-1.jpg",
      "images/projects/i-know-you/alessandro-rossi-anorak-crow-story-2.jpg",
    ],
  },
  {
    slug: "sprazzi-destate",
    title: "Sprazzi d'estate",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Spot illustration"],
    cover: "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-preview.jpg",
    images: [
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-01.jpg",
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-02.jpg",
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-03.jpg",
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-04.jpg",
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-05.jpg",
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-06.jpg",
      "images/projects/sprazzi-destate/alessandro-rossi-biss-summerspots-07.jpg",
    ],
  },
  {
    slug: "robotzzz",
    title: "Robotzzz",
    type: "Personal work",
    year: "2026",
    category: "personal",
    tags: ["Personal work", "Character design"],
    images: [
      "images/projects/robotzzz/ed_robots_01.jpg",
      "images/projects/robotzzz/ed_robots_02.jpg",
      "images/projects/robotzzz/ed_robots_03.jpg",
      "images/projects/robotzzz/ed_robots_04.jpg",
      "images/projects/robotzzz/ed_robots_05.jpg",
      "images/projects/robotzzz/ed_robots_06.jpg",
      "images/projects/robotzzz/ed_robots_07.jpg",
      "images/projects/robotzzz/ed_robots_08.jpg",
      "images/projects/robotzzz/ed_robots_09.jpg",
      "images/projects/robotzzz/ed_robots_10.jpg",
    ],
  },
  {
    slug: "domenico-starnone",
    title: "Domenico Starnone",
    type: "Cover",
    year: "2026",
    category: "cover",
    tags: ["Cover", "Portrait"],
    images: [
      "images/projects/domenico-starnone/alessandro-rossi-l-espresso.jpg",
    ],
  },
  {
    slug: "the-monferriner",
    title: "The Monferriner",
    type: "Cover",
    year: "2026",
    category: "cover",
    tags: ["Cover", "Poster"],
    images: [
      "images/projects/the-monferriner/alessandro-rossi-the-monferriner.jpg",
    ],
  },
  {
    slug: "scale-infinite",
    title: "Scale infinite",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Book Review"],
    images: [
      "images/projects/scale-infinite/alessandro-rossi-nyt-br-villacoco.jpg",
    ],
  },
  {
    slug: "abbracciarsi",
    title: "Abbracciarsi",
    type: "Poster",
    year: "2026",
    category: "children",
    tags: ["Children", "Poster"],
    images: [
      "images/projects/abbracciarsi/alessandro-rossi-internazionalekids-poster-02.jpg",
    ],
  },
  {
    slug: "temperatura-critica",
    title: "Temperatura critica",
    type: "Comic",
    year: "2026",
    category: "comics",
    tags: ["Comic", "Editorial"],
    cover: "images/projects/temperatura-critica/temperatura-critica-preview.jpg",
    images: [
      "images/projects/temperatura-critica/ed-temperatura-critica-1.jpg",
      "images/projects/temperatura-critica/ed-temperatura-critica-2.jpg",
    ],
  },
  {
    slug: "fili-damicizia",
    title: "Fili d'amicizia",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial"],
    images: [
      "images/projects/fili-damicizia/alessandro-rossi-review.jpg",
    ],
  },
  {
    slug: "stillhuman",
    title: "Matter of Instinct",
    type: "Personal work",
    year: "2026",
    category: "personal",
    tags: ["Personal work", "Poster"],
    images: [
      "images/projects/stillhuman/matterofinstinct-rossi-alessandro-2.jpg",
    ],
  },
  {
    slug: "sz-newsletter-parenting",
    title: "SZ Newsletter — Parenting",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Newsletter"],
    images: [
      "images/projects/sz-newsletter-parenting/alessandro-rossi-sz-newsletter-parenting.jpg",
    ],
  },
  {
    slug: "mai-abbastanza",
    title: "Mai abbastanza",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial"],
    images: [
      "images/projects/mai-abbastanza/alessandro-rossi-sz-newsletter-mental-health.jpg",
    ],
  },
  {
    slug: "donnafugata",
    title: "Intorno alla stessa tavola",
    type: "Editorial",
    year: "2026",
    category: "editorial",
    tags: ["Editorial", "Wine"],
    images: [
      "images/projects/donnafugata/rossi-intorno-alla-stessa-tavola.jpg",
    ],
  },
];
